Rename `mitractl` binary to `mitra`
https://codeberg.org/silverpill/mitra/issues/67

diff --git a/contrib/debian/postinst b/contrib/debian/postinst
--- a/contrib/debian/postinst
+++ b/contrib/debian/postinst
@@ -25,4 +25,11 @@ esac
 
 #DEBHELPER#
 
+# Reload (service file changed in mitra 4.0)
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    if [ -d /run/systemd/system ]; then
+        systemctl --system daemon-reload >/dev/null || true
+    fi
+fi
+
 exit 0
